---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - {{ .Values.gateway.hostname }}
  gateways:
  - bookinfo
  http:
  - match:
    - uri:
        exact: /
    redirect:
      uri: /productpage
  - match:
    - uri:
        exact: /- {{ .Values.gateway.uri }}
    - uri:
        prefix: /- {{ .Values.gateway.uri1 }}
    - uri:
        exact: /- {{ .Values.gateway.uri2 }}
    - uri:
        exact: /- {{ .Values.gateway.uri3 }}
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080

